#!/bin/bash

[[ ! -f /usr/bin/acpi ]] && echo "no acpi" && exit 0

coproc acpi_listen
trap 'kill $COPROC_PID' EXIT

while read -u "${COPROC[0]}" -a event; do
    /etc/conf.d/suspender "${event[@]}"
done