#!/bin/sh

[[ ! -f /usr/bin/scrot ]] && echo "install scrot"
[[ ! -f /usr/bin/convert ]] && echo "install imagemagick"

scrot /tmp/screen_locked.png
convert /tmp/screen_locked.png -gravity North -font Noto-Sans-Display-Bold -fill "#e866d6" -pointsize 170 -annotate +0+150 'LOCKED' /tmp/screen_locked.png
mogrify -scale 10% -scale 1000% /tmp/screen_locked.png
i3lock -i /tmp/screen_locked.png